# https://jupyterbook.org/en/stable/customize/config.html
name: quanttide-handbook-of-research-assistants
title: 量潮助研管理手册
author: 量潮科技
description: 量潮助研管理手册
# Jupyter Book Config
only_build_toc_files: true